# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\anand\OneDrive\เดสก์ท็อป\KMITL STUDY ONLINE\Code lab\Project-86\fandom_guiv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QGridLayout, QWidget, QVBoxLayout, QTextEdit, QDialog
from PyQt5.QtGui import QPixmap, QTextCursor
import cv2

class Ui_Background(object):
    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.resize(1300, 900)
        Background.setMinimumSize(QtCore.QSize(1300, 900))
        Background.setMaximumSize(QtCore.QSize(1300, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\anand\\OneDrive\\เดสก์ท็อป\\KMITL STUDY ONLINE\\Code lab\\Project-86\\banner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Background.setWindowIcon(icon)
        Background.setStyleSheet("background: url(:/shineilenabg/bg.jpg)")
        self.centralwidget = QtWidgets.QWidget(Background)
        self.centralwidget.setObjectName("centralwidget")
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.searchbutton.setGeometry(QtCore.QRect(560, 90, 161, 41))
        self.searchbutton.setStyleSheet("font: 24pt \"Angsana New\";\n"
"background-image: url(:/background/bg.jpg);")
        self.searchbutton.setObjectName("searchbutton")
        self.displaytext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displaytext.setEnabled(True)
        self.displaytext.setGeometry(QtCore.QRect(40, 140, 1211, 691))
        self.displaytext.setStyleSheet("background-image: url(:/input white/white screen.jpg);\n"
"font: 22pt \"Angsana New\";")
        self.displaytext.setObjectName("displaytext")
        self.inputtext = QtWidgets.QLineEdit(self.centralwidget)
        self.inputtext.setGeometry(QtCore.QRect(410, 10, 461, 71))
        self.inputtext.setStyleSheet("background-image: url(:/whitescreenbg/white screen.jpg);\n"
"font: 75 48pt \"Angsana New\";")
        self.inputtext.setObjectName("inputtext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(780, 180, 361, 291))
        self.label.setStyleSheet("background-image: url(:/whitescreenbg/white screen.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.displaytext.raise_()
        self.searchbutton.raise_()
        self.inputtext.raise_()
        self.label.raise_()
        Background.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Background)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        Background.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Background)
        self.statusbar.setObjectName("statusbar")
        Background.setStatusBar(self.statusbar)

        self.retranslateUi(Background)
        QtCore.QMetaObject.connectSlotsByName(Background)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "86 \"Eighty-Six\" Wiki Fandom"))
        self.searchbutton.setText(_translate("Background", "Search"))

    def searchu(self):
        result=self.inputtext.text()
        result=(result.upper())
        if result in ["LENA","VLADILENA","VLADILENA MILIZE","VLADILENA MILIZÉ","HANDLER ONE","BLOODY REINA","BLOODY REGINA","THE BLOODSTAINED QUEEN"]:
            f = open("characters\Vladilena Milize.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["ANJU EMMA","SNOW WITCH","ANJU","SNOWWITCH","EMMA"]:
            f = open("characters\Anju Emma.txt","r")
            self.displaytext.setPlainText(f.read())
            self.label.setPixmap(QPixmap("char pic\Anju Emma.jpg"))
        elif result in ["DAIYA IRMA","BLACK DOG","DAIYA","BLACKDOG","IRMA"]:
            f = open("characters\Daiya Irma.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["DUSTIN JAEGER","SAGITTARIUS","DUSTIN","JAEGER"]:
            f = open("characters\Dustin Yaeger.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["ERNST ZIMMERMAN","ERNST","ZIMMERMAN"]:
            f = open("characters\Ernst Zimmerman.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["ERWIN MARCEL","ERWIN","MARCEL"]:
            f = open("characters\Erwin Marcel.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["EUGENE RANTZ","EUGENE"]:
            f = open("characters\Eugene Rantz.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["FIDO"]:
            f = open("characters\Fido.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["FREDERICA ROSENFORT","FREDERICA","ROSENFORT","AUGUSTA FREDERICA ADEL-ADLER","AUGUSTA FREDERICA ADEL ADLER","AUGUSTA","ADEL-ADLER","ADEL ADLER"]:
            f = open("characters\Frederica Rosenfort.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["GRETHE WENZEL","GRETHE","WENZEL"]:
            f = open("characters\Grethe Wenzel.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["HARUTO KEATS","FALKE","HARUTO","KEATS"]:
            f = open("characters\Haruto Keats.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["HENRIETTA VON PENROSE","ANNETTE","RITA","MINERVA","HENRIETTA"]:
            f = open("characters\Henrietta von Penrose.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["JÉRÔME KARLSTAHL","JEROME KARLSTAHL","JÉRÔME","JEROME"]:
            f = open("characters\Jérôme Karlstahl.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["JOSEF VON PENROSE","JOSEF"]:
            f = open("characters\Josef von Penrose.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["KAIE TANIYA","KIRSCHBLÜTE","KIRSCHBLUTE","KAIE","TANIYA"]:
            f = open("characters\Kaie Taniya.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["KIRIYA NOUZEN","KIRIYA","KIRI","PALE RIDER","PALERIDER"]:
            f = open("characters\Kiriya Nouzen.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["KUJO NICO","SIRIUS","KUJO","NICO"]:
            f = open("characters\Kujo Nico.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["KURENA KUKUMILA","GUNSLINGER","GUN SLINGER","KURENA","KUKUMILA"]:
            f = open("characters\Kurena Kukumila.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["LERCHE","SEVEN YEAR OLD","SEVEN-YEAR-OLD","LERCHENLIED","CHAIKA"]:
            f = open("characters\Lerche.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["LUDMILA","MALINOVKA ONE","MALINOVKAONE"]:
            f = open("characters\Ludmila.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["MARGARETA MILIZÉ","MARGARETA MILIZE","MARGARETA"]:
            f = open("characters\Margareta Milizé.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["NINA RANTZ","NINA"]:
            f = open("characters\MNina Rantz.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["RAIDEN SHUGA","WEHWOLF","WEREWOLF","RAIDEN","SHUGA"]:
            f = open("characters\Raiden Shuga.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["REKI MICHIHI","HUALIAN","REKI","MICHIHI"]:
            f = open("characters\Reki Michihi.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["RICHARD ALTNER","RICHARD","ALTNER"]:
            f = open("characters\Richard Altner.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SHIDEN IIDA","CYCLOPS","CYCLOP","SHIDEN","IIDA"]:
            f = open("characters\Shiden Iida.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SHINEI NOUZEN","SHIN","UNDERTAKER","REAPER","SHINEI","BÁLEYGR","BALEYGR"]:
            f = open("characters\Shinei Nouzen.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SHOUREI NOUZEN","REI","SHOUREI","DULLAHAN","HEADLESS KNIGHT"]:
            f = open("characters\Shourei Nouzen.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["TERESA"]:
            f = open("characters\Teresa.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["THEOTO RIKKA","THEO","THEOTO","RIKKA","LAUGHING FOX","LAUGHINGFOX"]:
            f = open("characters\Theoto Rikka.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["TP","THERMOPYLAE","TIPPY","TEPPY","BLACKIE","WHITEY","CALICO","KITTY","REMARQUE"]:
            f = open("characters\TP.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["VÁCLAV MILIZÉ","VACLAV MILIZE","VÁCLAV","VACLAV","VÁCLAV MILIZE","VACLAV MILIZÉ"]:
            f = open("characters\Václav Milizé.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["VIKTOR IDINAROHK","VIKTOR","VIKA","VIKA THE KING OF CORPSES","THE KING OF CORPSES","THE SERPENT OF SHACKLES AND DECAY","GADYUKA","HVEÐRUNGR","HVEDRUNGER"]:
            f = open("characters\Viktor Idinarohk.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["WILLEM EHRENFRIED","WILLEM","EHRENFRIED"]:
            f = open("characters\Willem Ehrenfried.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["ZELENE BIRKENBAUM","ZELENE","BIRKENBAUM","MISTRESS","MERCILESS QUEEN"]:
            f = open("characters\Zelene Birkenbaum.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["FEDERAL REPUBLIC OF GIAD","GIAD","REPUBLIC OF GIAD","REPUBLIC GIAD","FEDERAL REPUBLIC"]:
            f = open("country\Federal Republic of Giad.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["GIADIAN EMPIRE","EMPIRE","GIADIAN"]:
            f = open("country\Giadian Empire.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["REPUBLIC OF SAN MAGNOLIA","SAN MAGNOLIA","SANMAGNOLIA"]:
            f = open("country\Republic of San Magnolia.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["UNITED KINGDOM OF ROA GRACIA","UNITED KINGDOM","ROA GRACIA","ROAGRACIA"]:
            f = open("country\ZUnited Kingdom of Roa Gracia.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["EIGHTY-SIXTH STRIKE PACKAGE","STRIKE PACKAGE","EIGHTY-SIXTH STRIKE","EIGHTY-SIXTH PACKAGE"]:
            f = open("ex\Eighty-Sixth Strike Package.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["LIST","CATEGORY"]:
            f = open("ex\list.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SIRIN"]:
            f = open("ex\Sirin.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SPEARHEAD SQUADRON","SPEARHEAD","SPEARHEAD SQUAD"]:
            f = open("ex\Spearhead Squadron.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["ALKONOST"]:
            f = open("mechs\FELDREẞ\Alkonost.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["BARUSHKA","BARUSHKA MATUSHKA","MATUSHKA","BARUSHKAMATUSHKA"]:
            f = open("mechs\FELDREẞ\Barushka Matushka.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["M1A4 JUGGERNAUT","M1A4","JUGGERNAUT"]:
            f = open("mechs\FELDREẞ\M1A4 Juggernaut.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["M4A3 VÁNAGANDR","M4A3","VÁNAGANDR","VANAGANDR","M4A3 VANAGANDR","M4A3 VÁNAGAND","M4A3 VANAGAND"]:
            f = open("mechs\FELDREẞ\M4A3 Vánagandr.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["XM2 REGINLEIF","REGINLEIF","XM2","REGINLEF","REGINLIF","REGINLIEF"]:
            f = open("mechs\FELDREẞ\XM2 Reginleif.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["M101 BARRETT","M101","BARRETT","BARRET","BARET","SCAVENGER","SCARVENGER","M101 BARRETT/SCAVENGER","M101 Scavenger"]:
            f = open("mechs\FELDREẞ support units\M101 Barrett.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["AMEISE","AMEIS","AMESE","AMISE"]:
            f = open("mechs\legion\Ameise.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["DINOSAURIA","DINO","DINOSAUR"]:
            f = open("mechs\legion\Dinosauria.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["EINTAGSFLIEGE","EINTAFLIEGE","EINTAGSFLIEGER","EINTAFLIEGER"]:
            f = open("mechs\legion\Eintagsfliege.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["GRAUWOLF","WOLF","GRAWWOLF","GROWWOLF"]:
            f = open("mechs\legion\Grauwolf.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["LÖWE","LOWE","LOWER","LÖWER"]:
            f = open("mechs\legion\Löwe.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["MORPHO","MOPHO"]:
            f = open("mechs\legion\Morpho.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["PHÖNIX","PHÖENIX","PHONIX","PHOENIX"]:
            f = open("mechs\legion\Phönix.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SELF-PROPELLED MINE","SELF PROPELLED MINE","PROPELLED MINE","SELF MINE"]:
            f = open("mechs\legion\Self-Propelled Mine.txt","r")
            self.displaytext.setPlainText(f.read())
        elif result in ["SKORPION","SCORPION"]:
            f = open("mechs\legion\Skorpion.txt","r")
            self.displaytext.setPlainText(f.read())
        else:
            self.displaytext.setPlainText("Not Found, You can type List or Category for more information")

import BGqrc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QMainWindow()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
