# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\anand\OneDrive\เดสก์ท็อป\KMITL STUDY ONLINE\Code lab\Project-86\fandom_guiv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QGridLayout, QWidget, QVBoxLayout, QTextEdit, QDialog
from PyQt5.QtGui import QPixmap, QTextCursor
import cv2
import database

class Ui_Background(object):
    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.resize(1300, 900)
        Background.setMinimumSize(QtCore.QSize(1300, 900))
        Background.setMaximumSize(QtCore.QSize(1300, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\anand\\OneDrive\\เดสก์ท็อป\\KMITL STUDY ONLINE\\Code lab\\Project-86\\banner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Background.setWindowIcon(icon)
        Background.setStyleSheet("background: url(:/shineilenabg/bg.jpg)")
        self.centralwidget = QtWidgets.QWidget(Background)
        self.centralwidget.setObjectName("centralwidget")
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.searchbutton.setGeometry(QtCore.QRect(560, 90, 161, 41))
        self.searchbutton.setStyleSheet("font: 24pt \"Angsana New\";\n"
"background-image: url(:/background/bg.jpg);")
        self.searchbutton.setObjectName("searchbutton")
        self.displaytext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displaytext.setEnabled(True)
        self.displaytext.setGeometry(QtCore.QRect(40, 140, 1211, 691))
        self.displaytext.setStyleSheet("background-image: url(:/input white/white screen.jpg);\n"
"font: 22pt \"Angsana New\";")
        self.displaytext.setObjectName("displaytext")
        self.inputtext = QtWidgets.QLineEdit(self.centralwidget)
        self.inputtext.setGeometry(QtCore.QRect(410, 10, 461, 71))
        self.inputtext.setStyleSheet("background-image: url(:/whitescreenbg/white screen.jpg);\n"
"font: 75 48pt \"Angsana New\";")
        self.inputtext.setObjectName("inputtext")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 830, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 830, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.displaytext.raise_()
        self.searchbutton.raise_()
        self.inputtext.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        Background.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Background)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        Background.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Background)
        self.statusbar.setObjectName("statusbar")
        Background.setStatusBar(self.statusbar)
        self.searchbutton.clicked.connect(self.searchu)

        self.retranslateUi(Background)
        self.pushButton.clicked.connect(self.displaytext.show) # type: ignore
        self.pushButton_2.clicked.connect(self.displaytext.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Background)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "86 \"Eighty-Six\" Wiki Fandom"))
        self.searchbutton.setText(_translate("Background", "Search"))
        self.pushButton.setText(_translate("Background", "Show"))
        self.pushButton_2.setText(_translate("Background", "Hide"))
        self.displaytext.setPlainText(_translate("Background", "    86―Eighty-Six― is a Japanese science fiction light novel series written by Asato Asato and illustrated by Shirabii. It began publication by ASCII Media Works under their Dengeki Bunko imprint in February 2017. The series is licensed in North America by Yen Press. \n  \n    A War Without Casualties The Republic of San Magnolia has long been under attack from the neighboring Giadian Empire's army of unmanned drones known as the Legion. After years of painstaking research, the Republic finally developed autonomous drones of their own, turning the one-sided struggle into a war without casualties-or at least, that's what the government claims. In truth, there is no such thing as a bloodless war. Beyond the fortified walls protecting the eighty-five Republic territories lies the nonexistent Eighty-Sixth Sector. The young men and women of this forsaken land are branded the Eighty-Six and, stripped of their humanity, pilot the unmanned weapons into battle. \n \n \n \n \n \n \n \n \n      Type List or Category for more information"))
    
    def data(self,char , FolName ,PicFol):
        f = open("{}\{}.txt".format(FolName,char),"r")
        img = cv2.imread('{}\{}.jpg'.format(PicFol,char)) 
        cv2.imshow('{}'.format(char), img) 
        self.displaytext.setPlainText(f.read())
    
    def searchu(self):
        result=self.inputtext.text()
        result=(result.upper())
        for i in database.data.keys():
            if result in (i).split(','):
                a,b,c = database.data[i]
                self.data(a,b,c)
                return
        self.displaytext.setPlainText("Not Found, You can type List or Category for more information")
    
import BGqrc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QMainWindow()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
