data = { ("LENA,VLADILENA,VLADILENA MILIZE,VLADILENA MILIZÉ,HANDLER ONE,BLOODY REINA,BLOODY REGINA,THE BLOODSTAINED QUEEN"):['Vladilena Milize' , 'characters' ,'char pic'],
	    ("ANJU EMMA,SNOW WITCH,ANJU,SNOWWITCH,EMMA"):['Anju Emma','characters','char pic'],
		("DAIYA IRMA,BLACK DOG,DAIYA,BLACKDOG,IRMA"):['Daiya Irma','characters','char pic'],
		("DUSTIN JAEGER,SAGITTARIUS,DUSTIN,JAEGER"):['Dustin Jaeger','characters','char pic'],
		("ERNST ZIMMERMAN,ERNST,ZIMMERMAN"):['Ernst Zimmerman','characters','char pic'],
		("ERWIN MARCEL,ERWIN,MARCEL"):['Erwin Marcel','characters','char pic'],
		("EUGENE RANTZ,EUGENE"):['Eugene Rantz','characters','char pic'],
		("FIDO"):['Fido','characters','char pic'],
		("FREDERICA ROSENFORT,FREDERICA,ROSENFORT,AUGUSTA FREDERICA ADEL-ADLER,AUGUSTA FREDERICA ADEL ADLER,AUGUSTA,ADEL-ADLER,ADEL ADLER"):['Frederica Rosenfort','characters','char pic'],
		("GRETHE WENZEL,GRETHE,WENZEL"):['Grethe Wenzel','characters','char pic'],
		("HARUTO KEATS,FALKE,HARUTO,KEATS"):['Haruto Keats','characters','char pic'],
		("HENRIETTA VON PENROSE,ANNETTE,RITA,MINERVA,HENRIETTA"):['Henrietta von Penrose','characters','char pic'],
		("JÉRÔME KARLSTAHL,JEROME KARLSTAHL,JÉRÔME,JEROME"):['Jérôme Karlstahl','characters','char pic'],
		("JOSEF VON PENROSE,JOSEF"):['Josef von Penrose','characters','char pic'],
		("KAIE TANIYA,KIRSCHBLÜTE,KIRSCHBLUTE,KAIE,TANIYA"):['Kaie Taniya','characters','char pic'],
		("KIRIYA NOUZEN,KIRIYA,KIRI,PALE RIDER,PALERIDER"):['Kiriya Nouzen','characters','char pic'],
		("KUJO NICO,SIRIUS,KUJO,NICO"):['Kujo Nico','characters','char pic'],
		("KURENA KUKUMILA,GUNSLINGER,GUN SLINGER,KURENA,KUKUMILA"):['Kurena Kukumila','characters','char pic'],
		("LERCHE,SEVEN YEAR OLD,SEVEN-YEAR-OLD,LERCHENLIED,CHAIKA"):['Lerche','characters','char pic'],
		("LUDMILA,MALINOVKA ONE,MALINOVKAONE"):['Ludmila','characters','char pic'],
		("MARGARETA MILIZÉ,MARGARETA MILIZE,MARGARETA"):['Margareta Milizé.txt','characters','char pic'],
		("NINA RANTZ,NINA"):['MNina Rantz','characters','char pic'],
		("RAIDEN SHUGA,WEHWOLF,WEREWOLF,RAIDEN,SHUGA"):['Raiden Shuga','characters','char pic'],
		("REKI MICHIHI,HUALIAN,REKI,MICHIHI"):['Reki Michihi','characters','char pic'],
		("RICHARD ALTNER,RICHARD,ALTNER"):['Richard Altner','characters','char pic'],
		("SHIDEN IIDA,CYCLOPS,CYCLOP,SHIDEN,IIDA"):['Shiden Iida','characters','char pic'],
		("SHINEI NOUZEN,SHIN,UNDERTAKER,REAPER,SHINEI,BÁLEYGR,BALEYGR"):['Shinei Nouzen','characters','char pic'],
		("SHOUREI NOUZEN,REI,SHOUREI,DULLAHAN,HEADLESS KNIGHT"):['Shourei Nouzen','characters','char pic'],
		("TERESA"):['Teresa','characters','char pic'],
		("THEOTO RIKKA,THEO,THEOTO,RIKKA,LAUGHING FOX,LAUGHINGFOX"):['Theoto Rikka','characters','char pic'],
		("TP,THERMOPYLAE,TIPPY,TEPPY,BLACKIE,WHITEY,CALICO,KITTY,REMARQUE"):['TP','characters','char pic'],
		("VÁCLAV MILIZÉ,VACLAV MILIZE,VÁCLAV,VACLAV,VÁCLAV MILIZE,VACLAV MILIZÉ"):['Václav Milize','characters','char pic'],
		("VIKTOR IDINAROHK,VIKTOR,VIKA,VIKA THE KING OF CORPSES,THE KING OF CORPSES,THE SERPENT OF SHACKLES AND DECAY,GADYUKA,HVEÐRUNGR,HVEDRUNGER"):['Viktor Idinarohk','characters','char pic'],
		("WILLEM EHRENFRIED,WILLEM,EHRENFRIED"):['Willem Ehrenfried','characters','char pic'],
		("ZELENE BIRKENBAUM,ZELENE,BIRKENBAUM,MISTRESS,MERCILESS QUEEN"):['Zelene Birkenbaum','characters','char pic'],
		("FEDERAL REPUBLIC OF GIAD,GIAD,REPUBLIC OF GIAD,REPUBLIC GIAD,FEDERAL REPUBLIC"):['Federal Republic of Giad','country','flag pic'],
		("GIADIAN EMPIRE,EMPIRE,GIADIAN"):['Giadian Empire','country','flag pic'],
		("REPUBLIC OF SAN MAGNOLIA,SAN MAGNOLIA,SANMAGNOLIA"):['Republic of San Magnolia','country','flag pic'],
		("UNITED KINGDOM OF ROA GRACIA,UNITED KINGDOM,ROA GRACIA,ROAGRACIA"):['ZUnited Kingdom of Roa Gracia','country','flag pic'],
		("EIGHTY-SIXTH STRIKE PACKAGE,STRIKE PACKAGE,EIGHTY-SIXTH STRIKE,EIGHTY-SIXTH PACKAGE"):['Eighty-Sixth Strike Package','ex','ex pic'],
		("LIST"):['list','ex','ex pic'],
		("CATEGORY"):['category','ex','ex pic'],
		("CHARACTERS,CHARACTER"):['characters','ex','ex pic'],
		("COUNTRY"):['country','ex','ex pic'],
		("GROUP,GROUPS"):['group','ex','ex pic'],
		("MECH,MECHS"):['mech','ex','ex pic'],
		("SIRIN"):['sirin','ex','ex pic'],
		("SPEARHEAD SQUADRON,SPEARHEAD,SPEARHEAD SQUAD"):['Spearhead Squadron','ex','ex pic'],
		("86,EIGHTY SIX,EIGHTYSIX"):['86','ex','ex pic'],
		("MILIZE,MILIZÉ"):['milize','ex','ex pic'],
		("ALKONOST"):['Alkonost','mechs\FELDREẞ','FELDREB pic'],
		("BARUSHKA,BARUSHKA MATUSHKA,MATUSHKA,BARUSHKAMATUSHKA"):['Barushka Matushka','mechs\FELDREẞ','FELDREB pic'],
		("M1A4 JUGGERNAUT,M1A4,JUGGERNAUT"):['M1A4 Juggernaut','mechs\FELDREẞ','FELDREB pic'],
		("M4A3 VÁNAGANDR,M4A3,VÁNAGANDR,VANAGANDR,M4A3 VANAGANDR,M4A3 VÁNAGAND,M4A3 VANAGAND"):['M4A3 Vánagandr','mechs\FELDREẞ','FELDREB pic'],
		("XM2 REGINLEIF,REGINLEIF,XM2,REGINLEF,REGINLIF,REGINLIEF"):['XM2 Reginleif','mechs\FELDREẞ','FELDREB pic'],
		("M101 BARRETT,M101,BARRETT,BARRET,BARET,SCAVENGER,SCARVENGER,M101 BARRETT/SCAVENGER,M101 Scavenger"):['M101 Barrett','mechs\FELDREẞ support units','FELDREB pic'],
		("AMEISE,AMEIS,AMESE,AMISE"):['Ameise','mechs\legion','Legion pic'],
		("DINOSAURIA,DINO,DINOSAUR"):['Dinosauria','mechs\legion','Legion pic'],
		("EINTAGSFLIEGE,EINTAFLIEGE,EINTAGSFLIEGER,EINTAFLIEGER"):['Eintagsfliege','mechs\legion','Legion pic'],
		("GRAUWOLF,WOLF,GRAWWOLF,GROWWOLF"):['Grauwolf','mechs\legion','Legion pic'],
		("LÖWE,LOWE,LOWER,LÖWER"):['Löwe','mechs\legion','Legion pic'],
		("MORPHO,MOPHO"):['Morpho','mechs\legion','Legion pic'],
		("PHÖNIX,PHÖENIX,PHONIX,PHOENIX"):['Phönix','mechs\legion','Legion pic'],
		("SELF-PROPELLED MINE,SELF PROPELLED MINE,PROPELLED MINE,SELF MINE"):['Self-Propelled Mine','mechs\legion','Legion pic'],
		("SKORPION,SCORPION"):['Skorpion','mechs\legion','Legion pic'],		
	    }