# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\anand\OneDrive\เดสก์ท็อป\KMITL STUDY ONLINE\Code lab\Project-86\fandom_guiv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Background(object):
    def setupUi(self, Background):
        Background.setObjectName("Background")
        Background.resize(1300, 900)
        Background.setMinimumSize(QtCore.QSize(1300, 900))
        Background.setMaximumSize(QtCore.QSize(1300, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\anand\\OneDrive\\เดสก์ท็อป\\KMITL STUDY ONLINE\\Code lab\\Project-86\\banner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Background.setWindowIcon(icon)
        Background.setStyleSheet("background: url(:/shineilenabg/bg.jpg)")
        self.centralwidget = QtWidgets.QWidget(Background)
        self.centralwidget.setObjectName("centralwidget")
        self.searchbutton = QtWidgets.QPushButton(self.centralwidget)
        self.searchbutton.setGeometry(QtCore.QRect(560, 90, 161, 41))
        self.searchbutton.setStyleSheet("font: 24pt \"Angsana New\";\n"
"background-image: url(:/background/bg.jpg);")
        self.searchbutton.setObjectName("searchbutton")
        self.displaytext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.displaytext.setEnabled(True)
        self.displaytext.setGeometry(QtCore.QRect(40, 140, 1211, 691))
        self.displaytext.setStyleSheet("background-image: url(:/input white/white screen.jpg);\n"
"font: 22pt \"Angsana New\";")
        self.displaytext.setObjectName("displaytext")
        self.inputtext = QtWidgets.QLineEdit(self.centralwidget)
        self.inputtext.setGeometry(QtCore.QRect(410, 10, 461, 71))
        self.inputtext.setStyleSheet("background-image: url(:/whitescreenbg/white screen.jpg);\n"
"font: 75 48pt \"Angsana New\";")
        self.inputtext.setObjectName("inputtext")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(780, 180, 361, 291))
        self.label.setStyleSheet("background-image: url(:/whitescreenbg/white screen.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.displaytext.raise_()
        self.searchbutton.raise_()
        self.inputtext.raise_()
        self.label.raise_()
        Background.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Background)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        Background.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Background)
        self.statusbar.setObjectName("statusbar")
        Background.setStatusBar(self.statusbar)

        self.retranslateUi(Background)
        QtCore.QMetaObject.connectSlotsByName(Background)

    def retranslateUi(self, Background):
        _translate = QtCore.QCoreApplication.translate
        Background.setWindowTitle(_translate("Background", "86 \"Eighty-Six\" Wiki Fandom"))
        self.searchbutton.setText(_translate("Background", "Search"))
import BGqrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Background = QtWidgets.QMainWindow()
    ui = Ui_Background()
    ui.setupUi(Background)
    Background.show()
    sys.exit(app.exec_())
